/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Thu Jan 21 17:56:48 CET 2010.
 */

package de.htwk.autolat.Connector.xmlrpc.parse;
import de.htwk.autolat.Connector.types.*;

import java.util.List;

@SuppressWarnings("unused")
public class ScoringOrderParser
{
    private static final Parser<ScoringOrder> inst =
        new AlternativeParser<ScoringOrder>(
            new StructFieldParser<ScoringOrder>(
                "Increasing",
                new Parser<ScoringOrder>()
                {
                    
                    public ScoringOrder parse(Object val) throws ParseErrorBase
                    {
                        return new Increasing(
                            );
                    }
                    
                }
                
            ),
            new AlternativeParser<ScoringOrder>(
                new StructFieldParser<ScoringOrder>(
                    "None",
                    new Parser<ScoringOrder>()
                    {
                        
                        public ScoringOrder parse(Object val) throws ParseErrorBase
                        {
                            return new None(
                                );
                        }
                        
                    }
                    
                ),
                new StructFieldParser<ScoringOrder>(
                    "Decreasing",
                    new Parser<ScoringOrder>()
                    {
                        
                        public ScoringOrder parse(Object val) throws ParseErrorBase
                        {
                            return new Decreasing(
                                );
                        }
                        
                    }
                    
                )
            )
        );
    
    public static Parser<ScoringOrder> getInstance()
    {
        return inst;
    }
    
}
