/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.xmlrpc.parse;
import de.htwk.autolat.Connector.types.*;

import java.util.List;

@SuppressWarnings("unused")
public class ServerInfoParser
{
    private static final Parser<ServerInfo> inst =
        new StructFieldParser<ServerInfo>(
            "ServerInfo",
            new Parser<ServerInfo>()
            {
                Parser<Version> protocolVersionParser = null;
                Parser<String> serverNameParser = null;
                Parser<Version> serverVersionParser = null;
                
                public ServerInfo parse(Object val) throws ParseErrorBase
                {
                    if (protocolVersionParser == null)
                        protocolVersionParser = new StructFieldParser<Version>(
                                                    "protocol_version",
                                                    VersionParser.getInstance());
                    if (serverNameParser == null)
                        serverNameParser = new StructFieldParser<String>(
                                               "server_name",
                                               StringParser.getInstance());
                    if (serverVersionParser == null)
                        serverVersionParser = new StructFieldParser<Version>(
                                                  "server_version",
                                                  VersionParser.getInstance());
                    return new ServerInfo(
                        protocolVersionParser.parse(val),
                        serverNameParser.parse(val),
                        serverVersionParser.parse(val));
                }
                
            }
            
        );
    
    public static Parser<ServerInfo> getInstance()
    {
        return inst;
    }
    
}
