/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Thu Jan 21 17:56:48 CET 2010.
 */

package de.htwk.autolat.Connector.xmlrpc.parse;
import de.htwk.autolat.Connector.types.*;

import java.util.List;

@SuppressWarnings("unused")
public class TaskDescriptionParser
{
    private static final Parser<TaskDescription> inst =
        new StructFieldParser<TaskDescription>(
            "TaskDescription",
            new Parser<TaskDescription>()
            {
                Parser<Documented<String>> taskSampleConfigParser = null;
                Parser<ScoringOrder> taskScoringOrderParser = null;
                
                public TaskDescription parse(Object val) throws ParseErrorBase
                {
                    if (taskSampleConfigParser == null)
                        taskSampleConfigParser = new StructFieldParser<Documented<String>>(
                                                     "task_sample_config",
                                                     new DocumentedParser<String>(StringParser.getInstance()));
                    if (taskScoringOrderParser == null)
                        taskScoringOrderParser = new StructFieldParser<ScoringOrder>(
                                                     "task_scoring_order",
                                                     ScoringOrderParser.getInstance());
                    return new TaskDescription(
                        taskSampleConfigParser.parse(val),
                        taskScoringOrderParser.parse(val));
                }
                
            }
            
        );
    
    public static Parser<TaskDescription> getInstance()
    {
        return inst;
    }
    
}
