/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.xmlrpc.parse;
import de.htwk.autolat.Connector.types.*;

import java.util.List;

@SuppressWarnings("unused")
public class VersionParser
{
    private static final Parser<Version> inst =
        new StructFieldParser<Version>(
            "Version",
            new Parser<Version>()
            {
                Parser<Integer> majorParser = null;
                Parser<Integer> minorParser = null;
                Parser<Integer> microParser = null;
                
                public Version parse(Object val) throws ParseErrorBase
                {
                    if (majorParser == null)
                        majorParser = new StructFieldParser<Integer>(
                                          "major",
                                          IntegerParser.getInstance());
                    if (minorParser == null)
                        minorParser = new StructFieldParser<Integer>(
                                          "minor",
                                          IntegerParser.getInstance());
                    if (microParser == null)
                        microParser = new StructFieldParser<Integer>(
                                          "micro",
                                          IntegerParser.getInstance());
                    return new Version(
                        majorParser.parse(val).intValue(),
                        minorParser.parse(val).intValue(),
                        microParser.parse(val).intValue());
                }
                
            }
            
        );
    
    public static Parser<Version> getInstance()
    {
        return inst;
    }
    
}
