/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.xmlrpc.serialize;
import de.htwk.autolat.Connector.types.*;

import java.util.List;
import redstone.xmlrpc.*;

@SuppressWarnings({"unused", "unchecked"})
public class DocumentedSerializer<A>
    implements Serializer<Documented<A>>
{
    private final Serializer<Documented<A>> serializer;
    
    public DocumentedSerializer(final Serializer<A> aSerializer)
    {
        serializer =
            new Serializer<Documented<A>>()
            {
                Serializer<A> contentsSerializer = null;
                Serializer<String> documentationSerializer = null;
                
                public Object serialize(Documented<A> val)
                {
                    if (contentsSerializer == null)
                        contentsSerializer = aSerializer;
                    if (documentationSerializer == null)
                        documentationSerializer = StringSerializer.getInstance();
                    
                    XmlRpcStruct inner = new XmlRpcStruct();
                    inner.put("contents", contentsSerializer.serialize(val.getContents()));
                    inner.put("documentation", documentationSerializer.serialize(val.getDocumentation()));
                    
                    XmlRpcStruct outer = new XmlRpcStruct();
                    outer.put("Documented", inner);
                    return outer;
                }
                
            }
            ;
    }
    
    public Object serialize(Documented<A> val)
    {
        return serializer.serialize(val);
    }
    
}
