/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.xmlrpc.serialize;
import de.htwk.autolat.Connector.types.*;

import java.util.List;
import redstone.xmlrpc.*;

@SuppressWarnings({"unused", "unchecked"})
public class InstanceSerializer
{
    private static final Serializer<Instance> inst =
        new Serializer<Instance>()
        {
            Serializer<String> tagSerializer = null;
            Serializer<String> contentsSerializer = null;
            
            public Object serialize(Instance val)
            {
                if (tagSerializer == null)
                    tagSerializer = StringSerializer.getInstance();
                if (contentsSerializer == null)
                    contentsSerializer = StringSerializer.getInstance();
                
                XmlRpcStruct inner = new XmlRpcStruct();
                inner.put("tag", tagSerializer.serialize(val.getTag()));
                inner.put("contents", contentsSerializer.serialize(val.getContents()));
                
                XmlRpcStruct outer = new XmlRpcStruct();
                outer.put("Instance", inner);
                return outer;
            }
            
        }
        ;
    
    public static Serializer<Instance> getInstance()
    {
        return inst;
    }
    
}
