/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Thu Jan 21 17:56:48 CET 2010.
 */

package de.htwk.autolat.Connector.xmlrpc.serialize;
import de.htwk.autolat.Connector.types.*;

import java.util.List;
import redstone.xmlrpc.*;

@SuppressWarnings({"unused", "unchecked"})
public class TaskDescriptionSerializer
{
    private static final Serializer<TaskDescription> inst =
        new Serializer<TaskDescription>()
        {
            Serializer<Documented<String>> taskSampleConfigSerializer = null;
            Serializer<ScoringOrder> taskScoringOrderSerializer = null;
            
            public Object serialize(TaskDescription val)
            {
                if (taskSampleConfigSerializer == null)
                    taskSampleConfigSerializer = new DocumentedSerializer<String>(StringSerializer.getInstance());
                if (taskScoringOrderSerializer == null)
                    taskScoringOrderSerializer = ScoringOrderSerializer.getInstance();
                
                XmlRpcStruct inner = new XmlRpcStruct();
                inner.put("task_sample_config", taskSampleConfigSerializer.serialize(val.getTaskSampleConfig()));
                inner.put("task_scoring_order", taskScoringOrderSerializer.serialize(val.getTaskScoringOrder()));
                
                XmlRpcStruct outer = new XmlRpcStruct();
                outer.put("TaskDescription", inner);
                return outer;
            }
            
        }
        ;
    
    public static Serializer<TaskDescription> getInstance()
    {
        return inst;
    }
    
}
