/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Thu Jan 21 17:56:48 CET 2010.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public class Decreasing implements ScoringOrder
{
    
    public Decreasing()
    {
    }
    
    public String toString()
    {
        return "Decreasing("
            + ")";
    }
    
    public boolean equals(Object other)
    {
        if (! (other instanceof Decreasing))
            return false;
        Decreasing oScoringOrder = (Decreasing) other;
        return true;
    }
    
    public int hashCode()
    {
        return 0;
    }
    
    public Increasing getIncreasing()
    {
        return null;
    }
    
    public None getNone()
    {
        return null;
    }
    
    public Decreasing getDecreasing()
    {
        return this;
    }
    
    public boolean isIncreasing()
    {
        return false;
    }
    
    public boolean isNone()
    {
        return false;
    }
    
    public boolean isDecreasing()
    {
        return true;
    }
    
}
