/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public class Documented<A>
{
    private final A contents;
    private final String documentation;
    
    public Documented(A contents, String documentation)
    {
        this.contents = contents;
        this.documentation = documentation;
    }
    
    public A getContents()
    {
        return contents;
    }
    
    public String getDocumentation()
    {
        return documentation;
    }
    
    public String toString()
    {
        return "Documented("
            + contents + ", "
            + documentation + ")";
    }
    
    public boolean equals(Object other)
    {
        if (! (other instanceof Documented<?>))
            return false;
        Documented<?> oDocumented = (Documented<?>) other;
        if (!contents.equals(oDocumented.getContents()))
            return false;
        if (!documentation.equals(oDocumented.getDocumentation()))
            return false;
        return true;
    }
    
    public int hashCode()
    {
        return
            contents.hashCode() * 1 +
            documentation.hashCode() * 37;
    }
    
}
