/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Thu Feb  4 18:33:35 CET 2010.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public class Increasing implements ScoringOrder
{
    
    public Increasing()
    {
    }
    
    public String toString()
    {
        return "Increasing("
            + ")";
    }
    
    public boolean equals(Object other)
    {
        if (! (other instanceof Increasing))
            return false;
        Increasing oScoringOrder = (Increasing) other;
        return true;
    }
    
    public int hashCode()
    {
        return
            0;
    }
    
    public Increasing getIncreasing()
    {
        return this;
    }
    
    public None getNone()
    {
        return null;
    }
    
    public Decreasing getDecreasing()
    {
        return null;
    }
    
    public boolean isIncreasing()
    {
        return true;
    }
    
    public boolean isNone()
    {
        return false;
    }
    
    public boolean isDecreasing()
    {
        return false;
    }
    
}
