/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public class Instance
{
    private final String tag;
    private final String contents;
    
    public Instance(String tag, String contents)
    {
        this.tag = tag;
        this.contents = contents;
    }
    
    public String getTag()
    {
        return tag;
    }
    
    public String getContents()
    {
        return contents;
    }
    
    public String toString()
    {
        return "Instance("
            + tag + ", "
            + contents + ")";
    }
    
    public boolean equals(Object other)
    {
        if (! (other instanceof Instance))
            return false;
        Instance oInstance = (Instance) other;
        if (!tag.equals(oInstance.getTag()))
            return false;
        if (!contents.equals(oInstance.getContents()))
            return false;
        return true;
    }
    
    public int hashCode()
    {
        return
            tag.hashCode() * 1 +
            contents.hashCode() * 37;
    }
    
}
