/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Thu Jan 21 17:56:48 CET 2010.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public interface ScoringOrder
{
    public Increasing getIncreasing();
    public None getNone();
    public Decreasing getDecreasing();
    public boolean isIncreasing();
    public boolean isNone();
    public boolean isDecreasing();
}
