/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public class Signed<A>
{
    private final A contents;
    private final String signature;
    
    public Signed(A contents, String signature)
    {
        this.contents = contents;
        this.signature = signature;
    }
    
    public A getContents()
    {
        return contents;
    }
    
    public String getSignature()
    {
        return signature;
    }
    
    public String toString()
    {
        return "Signed("
            + contents + ", "
            + signature + ")";
    }
    
    public boolean equals(Object other)
    {
        if (! (other instanceof Signed<?>))
            return false;
        Signed<?> oSigned = (Signed<?>) other;
        if (!contents.equals(oSigned.getContents()))
            return false;
        if (!signature.equals(oSigned.getSignature()))
            return false;
        return true;
    }
    
    public int hashCode()
    {
        return
            contents.hashCode() * 1 +
            signature.hashCode() * 37;
    }
    
}
