/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public interface TaskTree
{
    public Task getTask();
    public Category getCategory();
    public boolean isTask();
    public boolean isCategory();
}
