/*
 * Warning: This is a generated file. Edit at your own risk.
 * generated by Gen.hs on Wed Oct 28 18:26:49 CET 2009.
 */

package de.htwk.autolat.Connector.types;
import java.util.List;

@SuppressWarnings("unused")
public class Version
{
    private final int major;
    private final int minor;
    private final int micro;
    
    public Version(int major, int minor, int micro)
    {
        this.major = major;
        this.minor = minor;
        this.micro = micro;
    }
    
    public int getMajor()
    {
        return major;
    }
    
    public int getMinor()
    {
        return minor;
    }
    
    public int getMicro()
    {
        return micro;
    }
    
    public String toString()
    {
        return "Version("
            + major + ", "
            + minor + ", "
            + micro + ")";
    }
    
    public boolean equals(Object other)
    {
        if (! (other instanceof Version))
            return false;
        Version oVersion = (Version) other;
        if (major != oVersion.getMajor())
            return false;
        if (minor != oVersion.getMinor())
            return false;
        if (micro != oVersion.getMicro())
            return false;
        return true;
    }
    
    public int hashCode()
    {
        return
            new Integer(major).hashCode() * 1 +
            new Integer(minor).hashCode() * 37 +
            new Integer(micro).hashCode() * 1369;
    }
    
}
